### ISSUE TITLE
[Suggestion] Use Materialize or Material Design Lite

### ISSUE THREAD

**Issue by exp0nge** [ccnyacm/ccnyacm.github.io#15]
Consider using materialize (http://materializecss.com/) or MDL (http://www.getmdl.io/).

**Comment by venegu** [comment]
I considered using materialize before because I heard it is pretty awesome, but I actually prefer the lightness of purecss. Not only is it very customizable, it is also very lightweight because you only need to link to the specific stylesheets you need. If you don't need forms or tables then you simply don't link to those stylesheet in the head (although, currently I'm getting the entire source because I'm not sure what I may not need just yet). 

Additionally, I prefer everything that can reasonably be handled by css to be handled with css, there is no need to dampen load times across platforms for something to be animated with js. In my eyes each part has it's own role - I generally avoid js unless their is no way to quickly do what I need to do. By the same hand I also prefer little to no js in css frameworks.

I know material design lite is also pretty light and handles pretty much everything with css, but I noticed that both materialize and material design lite use sass. I really don't dig sass. That's just a personal preference though.

**Comment by DrkSephy** [comment]
We appreciate the feedback, but we'll be sticking with Pure. Closing this issue now.
